---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
```{r}
src='https://github.com/DrRaquelSanchez/WACountyCaBurden/raw/main/CtyCommBdn30.csv'

CtyCommBdn30=read.csv(src)
```

```{r}
library(reshape2)
CtyCommBdn30Long=melt(CtyCommBdn30, id.vars=c("Country"))
CtyCommBdn30Long

sort(CtyCommBdn30Long$value, decreasing = TRUE)
```
```{r}
CtyCommBdn30Long$value=CtyCommBdn30Long$value
```


```{r}
library(ggplot2)

base1=ggplot(data=CtyCommBdn30Long, aes(x=variable,value))
bar1=base1+geom_bar(stat = "identity")
bar1
```

```
```{r}
```{r}


bar2=bar1  +geom_bar(fill="blue", stat = "identity")
```

```{r}



titleText1='Top Communicable Diseases Contributing to Global Burden '
sourceText1='Source: World Health Organization'

bar3=bar2 + labs(title=titleText1,
                     x ="Communicable_Disease", 
                     y = "DALY",
                     caption = sourceText1) 
bar3
```
```


```{r echo=TRUE}
```{r}


library(scales)

bar4 = bar3 + scale_y_continuous(breaks=c(0.0,0.5,1.0,1.5,2.0),
                                   limits = c(0,2.0))
bar4 
```


```{r}

LABELS=mean(CtyCommBdn30Long$value)

bar5 = bar4 + geom_text(vjust=100, 
                          size = 100,
                          aes(x=variable, y = value,
                              label = LABELS))

bar5
```

```
